@url = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTc2MjU2NzEwNSwiZXhwIjoxNzYyNTgxNTA1fQ.5zim2vpGV0UPTTjJGe-7t-ijDWkxRlLCrQjFCkBpnMs

### Listar todos los alumnos
GET {{url}}/alumnos
Authorization: Bearer {{token}}

### Buscar alumno por ID
GET {{url}}/alumnos/1
Authorization: Bearer {{token}}

### Registrar un alumno nuevo
POST {{url}}/alumnos
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "nombre": "Carlos",
    "apellido": "Santana",
    "dni": "30123455"
}

### Registrar otro alumno
POST {{url}}/alumnos
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "nombre": "Laura",
    "apellido": "Pausini",
    "dni": "31987654"
}

### Eliminar un alumno por ID
DELETE {{url}}/alumnos/6
Authorization: Bearer {{token}}

### Modificar un alumno por ID
PUT {{url}}/alumnos/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "nombre": "carlos Alberto",
    "apellido": "Santana",
    "dni": "30123456"
}