@url = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...

### Todas las materias
GET {{url}}/materias
Authorization: Bearer {{token}}

### Materia por id
GET {{url}}/materias/1
Authorization: Bearer {{token}}

### Crear una nueva materia
POST {{url}}/materias
Content-Type: application/json
//Authorization: Bearer {{token}}

{
    "nombre": "Laboratorio de Programación IV",
    "codigo": "LP4",
    "año": 2025
}

### Eliminar una materia por ID
DELETE {{url}}/materias/3
Authorization: Bearer {{token}}

### Actualizar una materia por ID
PUT {{url}}/materias/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "nombre": "Laboratorio de Programación I",
    "codigo": "LPROG4",
    "año": 2025
}